### ISSUE TITLE
Graphics issue:Low framerate

### ISSUE THREAD

**Issue by PureWhite425** [antest1/GotoBrowser#17] opened 2019-05-25 17:16 UTC
I can enjoy a smooth 60FPS gameplay on Chrome,but the GotoBroser gives me some laggy feeling,maybe the framerate is only around 20FPS.
I have tested some other Kancolle html5 browsers,it seems they all have this issue.
Is this the issue caused by the integrated webview in android?
I think putting a independent brower can fix this issue.

**Comment by antest1** [comment] 2019-06-04 15:18
It is true that default webview has lower performance compared with other commercial browser like Chrome, Firefox, etc. Also, there is no alternatives for webview currently.

One solution might take the chromium source code, but I'm too busy to review and apply on GotoBrowser. Please understand for that orz

**Comment by spcharc** [comment] 2019-09-04 23:23
Webview is based on Chromium
> Since Android 4.4 (KitKat), the WebView component is based on the Chromium open source project.
link: https://developer.chrome.com/multidevice/webview/overview
I believe neither Chromium nor Webview can solve the problem. It may be caused by some rendering process not accelerated by GPU, and there would be no easy fix for this.
You can also compare the performance of Chrome with Chromium (or Firefox) on a PC, and you can see Chrome is really the best when it comes to optimization ...

**Comment by laplamgor** [comment] 2019-10-03 04:23
You may want to take a look at Crosswalk webview (https://github.com/crosswalk-project/crosswalk) which is basically a Chromium port to replace the default webview. 

Although it is unmaintained now and only running Chromium 53, the performance is still way better than the built-in webview and very close to the Chrome (running prototype on my S9+ w/ Pie). The only downside is a slightly bigger apk.

I will mod a gotobrowser with crosswalk when I have time, and hopefully submit a pull request within a month.

**Comment by laplamgor** [comment] 2019-10-21 16:01
After investing a lot of time in experimenting with a kcanotify fork and crosswalk(https://github.com/qly5213/kcanotify_h5-master), I finally have the conclusion.

Crosswalk (chromium 53) does not have the framerate issue but have a million minor issues, including: 
- huge lag when decoding mp3
- sprite randomly missing,
- slower than some old webview (53-64)
- GPU viewport raster not enabled by default
- no native mouse event support even using a physical mouse
- webview and crosswalk view cannot exist in the same activity
- almost 0 code sharing between webview and crosswalk (different namespace)
...

Meanwhile, I finally figure out that the framerate issue is due to KC using a lot of event based animation. In `main.js`: `createjs.Ticker.timingMode = createjs.Ticker.TIMEOUT`
will make the ticker heavily relies on timeout event which is not synced to requestAnimationFrame() calls. Since Chromium version 65(?), the ticker seems to be a lot more inaccurate/slower. It causes that some of the animation updates miss the frame updating timing.

I am not sure why Chromium will be slower but my guess is the Spectre attack mitigating around 2018 Q1 (browsers decreased the resolution of timers API) being poorly ported into the webview.

So the solution is simple:
replace the code above with `createjs.Ticker.timingMode = createjs.Ticker.RAF`

**Closed** 2019-10-27 06:55 UTC
